name: kairoz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_speed_dial: ^7.0.0
  http: ^1.2.2
  table_calendar: ^3.1.2
  fl_chart: ^0.69.0
  carousel_slider: ^5.0.0
  youtube_player_flutter: ^9.1.0
  postgres: ^3.4.0
  google_fonts: ^6.2.1
  syncfusion_flutter_calendar: ^27.1.52

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - .env
